### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jparkSF** [jparkSF/fullstack_project#3]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by mladenoff** [comment]
Rather than popping open an addition pre-populated log in window, your tour button should just dispatch the log in action.

**Comment by mladenoff** [comment]
I am getting some weirdness if I fill in the Sign In form and then click the Sign Up link. Take a look.

**Comment by jparkSF** [comment]
I was thinking about adding an animation for login. something like a typewriter thing, but i guess i won't really have time to invest on that lol.
so I just made the 'TAKE A TOUR' button to login as demo user right away.

I don't really understand how the bug was created because it wasn't like that when i was testing it.
however, it is also fixed.

No problems, boss

**Comment by mladenoff** [comment]
You definitely could do a typewriter animation if you wanted.

This is Jimmy's from last cohort: http://welp-i-guess.herokuapp.com/#/login

His code is here: https://github.com/jjl014/Welp

It'd be more slick to do it with an animated button click too.

**Comment by mladenoff** [comment]
Nicely done, lgtm.
