### ISSUE TITLE
PA Review: Create and search restaurants

### ISSUE THREAD

**Issue by jparkSF** [jparkSF/fullstack_project#6]
- [x] Adequate Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Search restaurant and receive results

**Comment by mladenoff** [comment]
Looks great, thanks!

Consider redirecting to the show page upon creation.
