### ISSUE TITLE
PA Review: Favorites

### ISSUE THREAD

**Issue by jparkSF** [jparkSF/fullstack_project#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Adequate Styling
- [x] Presentational Components
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by mladenoff** [comment]
Looks great. 

Is this bouncy effect deliberate on your part?
